app/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    note = db.Column(db.String(255))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id')) #lowercase Class name + variable -> OneToManyRelation

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True)
    pswd = db.Column(db.String(150))
    notes =  db.relationship('Note') #Capital Class name

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)

    # Define flask app environement config
    if app.config["ENV"] == "production":
        app.config.from_object("config.ProductionConfig")
    else:
        app.config.from_object("config.DevelopmentConfig")
    print(f' * Flask ENV is set to: {app.config["ENV"]}')

    # Config app sqlachemy database
    app.config['SQLALCHEMY_DATABASE_URI'] =  f'sqlite:///{DB_NAME}'
    db.init_app(app)

    # Define route with Blueprint
    from .views import views
    from .auth import auth
    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    # Check if database is created
    from .models import User, Note
    create_database(app)

    # Define login access to pages
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login' # redirection si login necessaire
    login_manager.init_app(app)

    # Get current user data from db
    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    #print(app.config)

    return app

def create_database(app):
    if not path.exists('app/'+ DB_NAME):
        db.create_all(app=app)
        print('Database created!')

app/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from .models import User, Note
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
import json

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['POST','GET'])
def login():
    if request.method == 'POST':
        name = request.form.get('name')
        pswd = request.form.get('pswd')

        user = User.query.filter_by(name=name).first()
        if user :
            if check_password_hash(user.pswd, pswd) :
                flash('Login successfull', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.user_homepage'))
            else:
                flash('Login failed', category='error')
        else:
            flash('Login failed', category='error')
    else :
        return render_template("auth/login.html")

@auth.route('/logout')
@login_required
def logout():
    return redirect(url_for('views.home'))

@auth.route('/sign-up', methods=['POST', 'GET'])
def sign_up():
    if request.method == 'POST':
        # getting form data
        name = request.form.get('name')
        pswd = request.form.get('pswd')
        # checking if user name already exist in db
        user = User.query.filter_by(name=name).first()
        if user :
            flash('Alias unavailable!', category='error')
            return render_template("auth/signup.html")
        else :
            # add new user in db
            db.session.add(User(name=name, pswd=generate_password_hash(pswd, method='sha256')))
            db.session.commit()
            # message for user
            flash('Account successfully created', category='success')
            # redirection to login page
            return redirect(url_for('auth.login'))
    else :
        return render_template("auth/signup.html")

@auth.route('/delete_note', methods=['POST'])
@login_required
def delete_note():
    # Recupere l'id de la note dans le body de la requete
    note = json.loads(request.data)
    note_id = note['noteId']
    # Recupere la note dans la db
    note = Note.query.get(note_id)
    # Verifie si la note appartient au current user
    if note :
        if note.user_id == current_user.id :
            db.session.delete(note)
            db.session.commit()
    return jsonify({})
    

app/views.py
import imp
from flask import Blueprint, render_template, request, flash
from flask_login import login_required, current_user
from .models import Note
from . import db

views = Blueprint('views', __name__)

@views.route('/hello')
def hello():

    return "<h1>hello</h1>"

@views.route('/', methods=['GET', 'POST'])
def home():
    text = request.form.get('text')
    if request.method == 'POST':
        flash('Message POST!', category='info')
        return render_template("views/home.html" , post_text="post ok "+str(text) )
    elif request.method == 'GET':
        flash('Message GET!', category='info')
        return render_template("views/home.html" , get_text="get ok "+str(text) )
    else :
        return render_template("views/home.html", name="audrey")

@views.route('/user', methods=['POST','GET'])
@login_required
def user_homepage():
    if request.method == 'POST':
        note = request.form.get('note')
        if len(note) >= 1 :
            # add new note in db to current user
            db.session.add(Note(note=note, user_id=current_user.id))
            db.session.commit()
            flash('Note added successfully!', category='success')
            
    return render_template("views/user.html", user=current_user)

app/templates/layout.html
<!doctype html>
<html lang="fr">
    <title>{% block title %}MyBlog{% endblock %}</title>
    <head>
        <meta charset="utf-8">
        <meta name="description" content="Free Web tutorials">
        <meta name="keywords" content="HTML, CSS, Flask, Python">
        <meta name="author" content="Audrey Ntep">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel ="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
    </head>
    <body>
        <header>
            {% block header %}{% endblock %}
        </header>
        <main>
            {% block main %}{% endblock %}
        </main>
        <script type ="text/javascript" src="{{ url_for('static', filename='js/index.js') }}"></script>
    </body>
</html>

app/templates/views/home.html
{% extends "layout.html" %}

{% block title %}MyBlog-home{% endblock %}

{% block header %}
    <h1>Home page - {{ name }}</h1>
{% endblock %}

{% block main %}

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <div>
        <h2>Ecrire un messsage secret :</h2>
        <form action="" method="POST">
            <label for="post_text">Votre message : </label>
            <input type="text" name="text" id="post_text"> 
            <button type="submit">OK</button>
        </form>
    </div>
    <p>Votre message post : {{ post_text }}</p>
    <div>
        <h2>Ecrire un messsage visible :</h2>
        <form action="" method="GET">
            <label for="get_text">Votre message : </label>
            <input type="text" name="text" id="get_text"> 
            <button type="submit">OK</button>
        </form>
    </div>
    <p>Votre message get : {{ get_text }}</p>
    <div>
        <p>
            <!--lien url fonction page_un()-->
            <a href="{{url_for('auth.login')}}">Login</a>
        </p>
        <p>
            <!--lien url fonction page_un()-->
            <a href="{{url_for('auth.sign_up')}}">Signup</a>
        </p>
    </div>
{% endblock %}

app/templates/views/user.html
{% extends "layout.html" %}

{% block title %}MyBlog-user{% endblock %}

{% block header %}
    <h1> hello {{ user.name }}</h1>
{% endblock %}
            
{% block main %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        {% endif %}
    {% endwith %}

{% if user %}
    <p>
        <a href="{{url_for('auth.logout')}}">Logout</a>
    </p>
{% endif %}
    <div>
        <h2>Write a note :</h2>
        <form action="" method="POST">
            <label for="note">New note : </label>
            <input type="text" name="note" id="note"> 
            <button type="submit">Add note</button>
        </form>
    </div>
    <p>Your notes :</p> 
    <ul>
        {% for note in user.notes %}
            <li>
                {{note.id}} {{note.note }}
                <button type="button" class="close" onClick="deleteNote({{note.id}})">
                    <span aria-hidden="true">&times;</span>
                </button>
            </li>
        {% endfor %}
    </ul>

{% endblock %}